// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA4jR_HVlxSUnKdoH2oo7tkfrVqAbUq18',
    appId: '1:793332803337:web:2cfd9abae86a7e033995d8',
    messagingSenderId: '793332803337',
    projectId: 'my-new-shorts',
    authDomain: 'my-new-shorts.firebaseapp.com',
    storageBucket: 'my-new-shorts.firebasestorage.app',
    measurementId: 'G-1991VBT31X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXShkYZwoAaNa0El4Ceq-x4MBSA7Ww16A',
    appId: '1:793332803337:android:de1bc76cf2b926e23995d8',
    messagingSenderId: '793332803337',
    projectId: 'my-new-shorts',
    storageBucket: 'my-new-shorts.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5DT5ZVrd9GVm2V376CtnmXnSvL5JhYEk',
    appId: '1:793332803337:ios:bd6b7a0dfa69f4253995d8',
    messagingSenderId: '793332803337',
    projectId: 'my-new-shorts',
    storageBucket: 'my-new-shorts.firebasestorage.app',
    iosClientId: '793332803337-jmnrq1024uj8qlvm8uk19pap7gjee6vq.apps.googleusercontent.com',
    iosBundleId: 'com.example.newShortsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5DT5ZVrd9GVm2V376CtnmXnSvL5JhYEk',
    appId: '1:793332803337:ios:bd6b7a0dfa69f4253995d8',
    messagingSenderId: '793332803337',
    projectId: 'my-new-shorts',
    storageBucket: 'my-new-shorts.firebasestorage.app',
    iosClientId: '793332803337-jmnrq1024uj8qlvm8uk19pap7gjee6vq.apps.googleusercontent.com',
    iosBundleId: 'com.example.newShortsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA4jR_HVlxSUnKdoH2oo7tkfrVqAbUq18',
    appId: '1:793332803337:web:97b63c554721f8063995d8',
    messagingSenderId: '793332803337',
    projectId: 'my-new-shorts',
    authDomain: 'my-new-shorts.firebaseapp.com',
    storageBucket: 'my-new-shorts.firebasestorage.app',
    measurementId: 'G-G6SYMNKMQX',
  );

}